dailyfresh/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^user/', include('user_manage.urls')),
    url(r'^goods/', include('goods_manage.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^cart/', include('cart_manage.urls')),
    url(r'^order/', include('order_manage.urls')),
]

user_manage/urls.py
from django.conf.urls import url
from user_manage import views

urlpatterns = [
    url(r'^register/$', views.register),
    url(r'^register_handle/$', views.register_handle),
    url(r'^login/$', views.login),
    url(r'^login_handle/$', views.login_handle),
    url(r'^logout', views.logout),
    url(r'^info/$', views.info),
    url(r'^order/$', views.order),
    url(r'^user_order(\d+)/$', views.user_center_order),
    url(r'^site/$', views.site),
]

order_manage/models.py
from django.db import models

class OrderInfo(models.Model):
    oid = models.CharField(max_length=20, primary_key=True)
    user = models.ForeignKey('user_manage.UserInfo')
    odate = models.DateTimeField(auto_now=True)
    oIsPay = models.BooleanField(default=False)
    ototal = models.DecimalField(max_digits=6, decimal_places=2)
    oaddress = models.CharField(max_length=150)

class OrderDetailInfo(models.Model):
    goods = models.ForeignKey('goods_manage.GoodsInfo')
    order = models.ForeignKey(OrderInfo)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    count = models.IntegerField()

user_manage/models.py
from django.db import models

# Create your models here.
class UserInfo(models.Model):
    uname =  models.CharField(max_length=20)  # 用户名
    upwd = models.CharField(max_length=40)  # 密码
    uemail = models.CharField(max_length=30)  # 邮箱
    ureceive = models.CharField(max_length=20, default='')  # 快递接收者
    uadress = models.CharField(max_length=120, default='')  # 送货地址
    uzipcode = models.CharField(max_length=6, default='')  # 邮编
    uphonenumber = models.CharField(max_length=11, default='')  # 电话号码
    class Meta:
        db_table = 'userinfo'

user_manage/views.py
#coding = utf-8
from django.core.paginator import Paginator
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from hashlib import sha1

from goods_manage.models import GoodsInfo
from order_manage.models import OrderInfo, OrderDetailInfo
from user_manage import login_decorator
from user_manage.models import UserInfo


def uname_exits(request):
    uname = request.GET.get('uname')
    count = UserInfo.objects.filter(uname=uname).count()
    return JsonResponse({'count': count})


def register(request):
    return render(request, 'user_manage/register.html')

def register_handle(request):
    post = request.POST
    uname = post['user_name']
    upwd = post['pwd']
    upwd2 = post['cpwd']
    uemail = post['email']
    if upwd2 != upwd:
        return redirect('/user/register/')
    sha = sha1()
    sha.update(upwd.encode('utf8'))
    upwd3 = sha.hexdigest()
    userinfo = UserInfo()
    userinfo.uname = uname
    userinfo.upwd = upwd3
    userinfo.uemail = uemail
    userinfo.save()
    return redirect('/user/login/')

def login(request):
    uname = request.COOKIES.get('uname', '')   # 从cookie中取用户名，取不到置为空
    context = {'title': '登录', 'error_name': 0, 'error_pwd': 0, 'uname': uname}
    return render(request, 'user_manage/login.html', context)

def login_handle(request):
    post = request.POST
    uname = post['username']
    upwd = post['pwd']
    remember_name = post.get('remmamber_name', 0)
    user = UserInfo.objects.filter(uname=uname)
    if(len(user) == 1):
        sha = sha1()
        sha.update(upwd.encode('utf8'))
        if(sha.hexdigest() == user[0].upwd):
            url = request.COOKIES.get('url', '/goods/index/')  # 登录成功跳转到先前的url
            red = HttpResponseRedirect(url)  # HttpResponseRedirect继承于HttpResponse.
            if(remember_name != 0):
                red.set_cookie('uname', uname)
            else:
                red.set_cookie('uname', uname, max_age=-1)
            request.session['user_id'] = user[0].id
            request.session['user_name'] = uname
            return red
        else:
            context = {'title': '登录', 'error_name': 0, 'error_pwd': 1, 'uname': uname, 'upwd': upwd}
            return render(request, 'user_manage/login.html', context)


    else:
        context = {'title': '登录', 'error_name': 1, 'error_pwd': 0, 'uname': uname, 'upwd': upwd}
        return render(request, 'user_manage/login.html', context)

def logout(request):
    request.session.flush()
    return redirect('/goods/index/')

@login_decorator.login
def info(request):
    goods_ids = request.COOKIES.get('goods_id', '')
    goods_ids1 = goods_ids.split(',')
    goods_list = []
    for goods_id in goods_ids1:
        try:  # 这里加个异常判断不然goods_id为空的话就会抛异常,空字符串不能转为int
            goods_list.append(GoodsInfo.objects.get(id=int(goods_id)))
        except ValueError:
            pass
    uname = request.session.get('user_name', 'zhangsan')
    uemail = UserInfo.objects.get(pk=request.session['user_id']).uemail
    context = {'uname': uname, 'uemail': uemail, 'page_name': 1, 'goods_list': goods_list}
    return render(request, 'user_manage/user_center_info.html', context)

@login_decorator.login
def order(request):
    context = {'page_name': 1}
    return render(request, 'user_manage/user_center_order.html', context)

@login_decorator.login
def site(request):
    user = UserInfo.objects.filter(pk=request.session['user_id'])[0]  # 返回的是一个queryset集合，集合没有save()方法，取第一个元素即可.
    if request.method == 'POST':  # 区分超链接和POST请求，如果是超链接请求，不执行if块
        post = request.POST
        user.ureceive = post.get('receiver')
        user.uadress = post.get('address')
        user.uzipcode = post.get('zipcode')
        user.uphonenumber = post.get('phonenumber')
        user.save()
    context = {'title': '用户中心', 'user': user, 'page_name': 1}
    return render(request, 'user_manage/user_center_site.html', context)

@login_decorator.login
def user_center_order(request, pageindex):
    uid = request.session.get('user_id')
    orderinfos = OrderInfo.objects.filter(user_id=uid).order_by('oIsPay', '-oid')

    # print(type(orderinfos))
    paginator = Paginator(orderinfos, 2)
    page = paginator.page(int(pageindex))

    context = {'orderinfos': orderinfos, 'paginator': paginator, 'page': page}
    return render(request, 'user_manage/user_center_order.html', context)

templates/user_manage/login.html
{% extends 'base_foot.html' %}

{% block head %}
<script>
$(function () {
    name_error = false;
    pwd_error = false;
    if({{ error_name }}==1)
    {
        $('.user_error').html('用户名输入错误').show();
    }

    if({{ error_pwd }}==1){
        $('.pwd_error').html('密码输入错误').show();

    }
    $('.name_input').blur(function () {
        if($('.name_input').val().length==0){
            $('.user_error').html('请输入用户名').show();
            name_error = false;
        }
        else {
            $('.user_error').hide();
            name_error = true;
        }
    });

    $('.pass_input').blur(function () {
        if($('.pass_input').val().length==0){
            $('.pwd_error').html('请输入密码').show();
            pwd_error = false;
        }
        else {
            $('.pwd_error').hide();
            pwd_error = true;
        }
    });
});

</script>
{% endblock head%}

{% block  content%}
	<div class="login_top clearfix">
		<a href="/goods/index/" class="login_logo"><img src="/static/images/logo02.png"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="/user/register/">立即注册</a>
				</div>
				<div class="form_input">
					<form action="/user/login_handle/" method="post">
                        {% csrf_token %}
						<input type="text" name="username" class="name_input" value="{{ uname }}" placeholder="请输入用户名">
						<div class="user_error">输入错误</div>
						<input type="password" name="pwd" class="pass_input" value="{{ upwd }}" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="remember_name" value="1" checked="checked">
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>

{% endblock content%}

templates/user_manage/register.html
{% extends 'base_foot.html' %}

{% block head %}
	<script type="text/javascript" src="/static/js/register.js"></script>
{% endblock head%}

{% block content %}
	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo" href="/goods/index/"><img src="/static/images/logo02.png"></a>
			<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="/user/login/">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form action="/user/register_handle/" method="post">
                    {% csrf_token %}
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="user_name" id="user_name">
						<span class="error_tip">提示信息</span>
					</li>					
					<li>
						<label>密码:</label>
						<input type="password" name="pwd" id="pwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="cpwd" id="cpwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="email" id="email">
						<span class="error_tip">提示信息</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”天天生鲜用户使用协议“</label>
						<span class="error_tip2">提示信息</span>
					</li>
					<li class="reg_sub">
						<input type="submit" value="注 册" name="">
					</li>
				</ul>				
				</form>
			</div>

		</div>

	</div>
{% endblock content %}

templates/user_manage/user_center_info.html
{% extends 'goods_manage/base.html' %}

 {% block content %}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/user/info/" class="active">· 个人信息</a></li>
				<li><a href="/user/user_order1/">· 全部订单</a></li>
				<li><a href="/user/site/">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{ uname }}</li>
							<li><span>邮箱：</span>{{ uemail }}</li>
						</ul>
				</div>
				
				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="goods_type_list clearfix">
                        {% for goods in goods_list%}
				<li>
					<a href="/goods/{{ goods.id }}/"><img src="/static/{{ goods.gpic }}"></a>
					<h4><a href="/goods/{{ goods.id }}/">{{ goods.gtitle }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ goods.gprice }}</span>
						<span class="unit">{{ goods.gprice }}/{{ goods.gunit }}</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
                        {% endfor %}

			</ul>
		</div>
		</div>
	</div>

 {% endblock content %}

templates/user_manage/user_center_order.html
{% extends 'goods_manage/base.html' %}

{% block head %}
  <script>
$(function () {  // 计算小计
    $('.col04').each(function () {
          price=parseFloat($(this).prev().prev().find('span').text());
          count=parseFloat($(this).prev().text());
          xiaoji=price*count;
          $(this).text(xiaoji.toFixed(2));
      })
})


  </script>
{% endblock head %}

 {% block content %}

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/user/info/">· 个人信息</a></li>
				<li><a href="/user/user_order1/" class="active">· 全部订单</a></li>
				<li><a href="/user/site/">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>
             {% for order in page %}
				<ul class="order_list_th w978 clearfix">
					<li class="col01">{{ order.odate }}</li>
					<li class="col02">订单号：{{ order.oid }}</li>
					<li class="col02 stress">未支付</li>		
				</ul>

				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
                                {% for orderdetail in order.orderdetailinfo_set.all %}
								<ul class="order_goods_list clearfix">					
									<li class="col01"><img src="/static/{{ orderdetail.goods.gpic }}"></li>
                                    <li class="col02">{{ orderdetail.goods.gtitle|slice:'10' }}<em><span id="single_price">{{ orderdetail.price }}</span>元/{{ orderdetail.goods.gunit }}</em></li>
									<li class="col03">{{ orderdetail.count }}</li>
									<li class="col04"></li>
								</ul>
								{% endfor %}
							</td>
							<td width="15%">{{ order.ototal }}</td>
							<td width="15%">待付款</td>
							<td width="15%"><a href="#" class="oper_btn">去付款</a></td>
						</tr>
					</tbody>
				</table>
             {% endfor  %}
				


				<div class="pagenation">
					  {% if page.has_previous %}
                <a href="/user/user_order{{ page.previous_page_number }}/">上一页</a>
                {% endif %}

                {% for index in page.paginator.page_range %}
                {% if index == page.number %}
				<a href="#" class="active">{{ index }}</a>
                {% else %}
                    <a href="/user/user_order{{ index }}/">{{ index }}</a>
                {% endif %}
                {% endfor %}

                {% if page.has_next %}
                <a href="/user/user_order{{ page.next_page_number }}/">下一页</a>
                {% endif %}
				</div>
		</div>
	</div>

{% endblock content %}

templates/user_manage/user_center_site.html
{% extends 'goods_manage/base.html' %}
 {% block content %}

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/user/info/">· 个人信息</a></li>
				<li><a href="/user/user_order1/">· 全部订单</a></li>
				<li><a href="/user/site/" class="active">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
						<dt>当前地址：</dt>
						<dd>{{ user.uadress }}   {{ user.ureceive }}  {{ user.uphonenumber }}</dd>
					</dl>					
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<form action="/user/site/" method="post">
                        {% csrf_token %}
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="receiver" value="{{ user.ureceive }}">
						</div>
						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea class="site_area" name="address">{{ user.uadress }}</textarea>
						</div>
						<div class="form_group">
							<label>邮编：</label>
							<input type="text" name="zipcode" value="{{ user.uzipcode }}">
						</div>
						<div class="form_group">
							<label>手机：</label>
							<input type="text" name="phonenumber" value="{{ user.uphonenumber }}">
						</div>

						<input type="submit" name="" value="提交" class="info_submit">
					</form>
				</div>
		</div>
	</div>

{% endblock content %}